# Site settings
title: Just For You Coach
email: justforyoucoach@bellsouth.net
phone: 256-837-2287
description: >- # this means to ignore newlines until "baseurl:"
  Local, family-owned business out of Hartselle, Alabama for over
  12 years. Let us take you where you need to go!
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter: https://twitter.com/JustForYouCoach
instagram:  https://www.instagram.com/explore/locations/1028052589/
facebook: https://www.facebook.com/Just-For-You-Coach-Casino-Trips-404242349765350/

# Build settings
source: src
destination: dist
markdown: kramdown
plugins:
  - jekyll-autoprefixer

autoprefixer:
  browsers:
    - last 2 versions

# Include
include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
